FLAGS=-D _DEBUG -ggdb3 -std=c++17 -O0 -Wall -Wextra -Weffc++ -Waggressive-loop-optimizations\
	-Wc++14-compat -Wmissing-declarations -Wcast-align -Wcast-qual -Wchar-subscripts\
	-Wconditionally-supported -Wconversion -Wctor-dtor-privacy -Wempty-body -Wfloat-equal\
	-Wformat-nonliteral -Wformat-security -Wformat-signedness -Wformat=2 -Winline -Wlogical-op\
	-Wnon-virtual-dtor -Wopenmp-simd -Woverloaded-virtual -Wpacked -Wpointer-arith -Winit-self\
	-Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel\
	-Wstrict-overflow=2 -Wsuggest-attribute=noreturn -Wsuggest-final-methods\
	-Wsuggest-final-types -Wsuggest-override -Wswitch-default -Wswitch-enum -Wsync-nand\
	-Wundef -Wunreachable-code -Wunused -Wuseless-cast -Wvariadic-macros -Wno-literal-suffix\
	-Wno-missing-field-initializers -Wno-narrowing -Wno-old-style-cast -Wno-varargs\
	-Wstack-protector -fcheck-new -fsized-deallocation -fstack-protector -fstrict-overflow\
	-flto-odr-type-merging -fno-omit-frame-pointer -Wlarger-than=8192 -Wstack-usage=8192 -pie\
	-fPIE -Werror=vla -fsanitize=address,alignment,bool,bounds,enum,float-cast-overflow,$\
	float-divide-by-zero,integer-divide-by-zero,leak,nonnull-attribute,null,object-size,$\
	return,returns-nonnull-attribute,shift,signed-integer-overflow,undefined,unreachable,$\
	vla-bound,vptr

INCL=-I./include/

OBJ_DIR=./objects/

SRC_DIR=./source/

GPP=g++ $(FLAGS) $(INCL)

OBJECTS=$(OBJ_DIR)verify_funcs.o $(OBJ_DIR)stack_funcs.o\
	$(OBJ_DIR)proc_funcs.o ../common.o $(OBJ_DIR)processor.o

spu: $(OBJECTS)
	$(GPP) $(OBJECTS) -o spu

$(OBJ_DIR)processor.o: $(SRC_DIR)processor.cpp
	$(GPP) -c $(SRC_DIR)processor.cpp -o $(OBJ_DIR)processor.o

$(OBJ_DIR)verify_funcs.o: $(SRC_DIR)verify_funcs.cpp
	$(GPP) -c $(SRC_DIR)verify_funcs.cpp -o $(OBJ_DIR)verify_funcs.o

$(OBJ_DIR)stack_funcs.o: $(SRC_DIR)stack_funcs.cpp
	$(GPP) -c $(SRC_DIR)stack_funcs.cpp -o $(OBJ_DIR)stack_funcs.o

$(OBJ_DIR)proc_funcs.o: $(SRC_DIR)proc_funcs.cpp
	$(GPP) -c $(SRC_DIR)proc_funcs.cpp -o $(OBJ_DIR)proc_funcs.o
